name: Deploy React App

# This workflow is triggered manually from the Actions tab
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the app to deploy (e.g., temp-app, timer-app)'
        required: true
        type: string

# Allow GITHUB_TOKEN to write to gh-pages branch
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '${{ inputs.app_name }}/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./${{ inputs.app_name }}

      - name: Build application
        run: npm run build
        working-directory: ./${{ inputs.app_name }}

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This is the directory where your app's build output is located
          path: ./${{ inputs.app_name }}/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
